services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: nina_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: nina_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: nina_db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: nina_phpmyadmin
      environment:
          PMA_HOST: db
          PMA_PORT: 3306
          MYSQL_ROOT_PASSWORD: root
      ports:
          - "8080:80"
      networks:
          - laravel
      depends_on:
          - db

networks:
  laravel:

volumes:
  db-data:
